#!/bin/bash

if [ -z "$1" -o -z "$2" ]; then
    echo "usage: init-plotty project-name log-dir [user-name]"
    echo ""
    echo "Initialises a new plotty instance in your home folder, named project-name."
    echo "Logs will be initialized based on the directory based on the command line."
    echo "If user-name was specified, the instance will be created in that user's home."
    echo "This will then be accessible from http://squirrel/plotty/user-name/project-name/"
    exit
fi

PROJECT_NAME=$1
LOG_DIR=$2

USER=""
if [  -z "$3" ]; then
    USER=`whoami`
else
    USER=$3
fi

USER_HOME="/home/$USER"
if [[ !( -d $USER_HOME ) ]]; then
    echo "ERROR: invalid user $USER"
    exit
fi

if [[ !( -d $USER_HOME/plotty ) ]]; then
    mkdir $USER_HOME/plotty
fi

PLOTTY_ROOT=$USER_HOME/plotty/$PROJECT_NAME

if [[ -d $PLOTTY_ROOT ]]; then
    echo "ERROR: project $PROJECT_NAME already exists for user $USER"
    exit
fi

echo "---> Creating directory structure in $PLOTTY_ROOT"

mkdir $PLOTTY_ROOT
ln -s $LOG_DIR $PLOTTY_ROOT/log

mkdir $PLOTTY_ROOT/app
mkdir $PLOTTY_ROOT/cache
mkdir $PLOTTY_ROOT/cache/logs
mkdir $PLOTTY_ROOT/cache/graphs

echo "---> Checking out source code to $PLOTTY_ROOT"
hg clone -r default ssh://squirrel.moma//home/mercurial/all/shared/plotty $PLOTTY_ROOT/app/plotty > /dev/null
if [[ $? -ne 0 ]]; then
    echo "ERROR: failed to check code out from mercurial"
    exit
fi

echo "---> Moving instance files to correct locations"
cp $PLOTTY_ROOT/app/plotty/server.wsgi $PLOTTY_ROOT/app/server.wsgi
cp $PLOTTY_ROOT/app/plotty/database.sqlite3.default $PLOTTY_ROOT/cache/database.sqlite3

echo "---> Fixing permissions for apache"
chmod -R a+r $PLOTTY_ROOT
chmod -R a+rw $PLOTTY_ROOT/cache
#chmod -R a+r $PLOTTY_ROOT/log

echo ""
echo "Done!"
echo "The new plotty instance is at $PLOTTY_ROOT"
echo "To start using it, populate the logs folder you specified ($LOG_DIR)"
echo "with folders of logs, then visit http://squirrel.anu.edu.au/plotty/$USER/$PROJECT_NAME/"
